### ISSUE TITLE
Unable to get it work

### ISSUE THREAD

**Issue by rushenn** [crystalui/angular-lightbox#1]
I had setup everything as per the documentation but I'm getting the following error in the browser console.

`ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

In my module, I'm not loading the `BrowserModule` but for whatever reason, it keeps firing the above error.

**Comment by drozhzhin-n-e** [comment]
@rushenn this is fixed in version 1.0.1. I guess I did not publish the update.

**Comment by rushenn** [comment]
@drozhzhin-n-e Yeah, I have the latest 1.0.3 and I'm still facing this issue.

**Comment by drozhzhin-n-e** [comment]
@rushenn updates are included in version 1.0.4

**Comment by rushenn** [comment]
Thank you
